### ISSUE TITLE
Would be a talk for coworking for a building system in c++? 

### ISSUE THREAD

**Issue by ltaoist** [Phytolizer/Build-System-in-C#1]
Hello!

I also would try a test for do a building system; for more, I want to "move" the libreoffice into it.

Are you interesting? Feel free to a talk, my email -- [ltaoist@163.com](mailto:ltaoist@163.com) -- tagged in "build system" if a email.

Thanks!

**Comment by Phytolizer** [comment]
Sure, I'd be interested in trying to flesh out this idea more. The issue with building larger C++ projects is caching; this currently does no checking to see if your code actually needs rebuilding, which is fine for a fresh clone but not great for development and iteration speed.

LibreOffice is a lofty goal; if we can get it working, that would be a sure sign that the build system covers a lot of ground!

**Comment by Phytolizer** [comment]
FWIW, I have a much more powerful version of the original C code here: https://github.com/Phytolizer/morth/blob/main/c-pure/coolbuild.h

The code in this repo was kind of the starting point for me, but I wanted to get used to using it in actual projects; I should backport those changes into this repo.

**Comment by ltaoist** [comment]
Good Job! I think you have a good start for coding!

Sorry I don't know what is mean to "Porth but More", and how it connect to "morth".

Personally, I consider "the building system" will be created as following:

=====================

Level1 --- Has a good concept on `building practices management`, and "the programs" runs with representative demo.

Level2 --- Has a frontier idea on why building system is, how building system is, or what building system is, and work well; do things in transformative

Level3 --- Has a good balance on "structure" and "impact"

=====================

Mostly, for now, I try to think what a role should be a building system in contemporary, and I crash. When I talk to my friend, we think building system is actually have three function:

(A) Connecting to compiler options setup, linking object files to executable file

(B) Dependence management and automation

(C) Incremental build

Such is good, and then we cannot have more idea.

However, there still two think I don't finish:

(X) Understanding the libreoffice structure, so I can go on to Level 1 and function A, B. Actually, the interesting point may be libreoffice is complex enough, to it is good for a example as a "building target". I got some material, but more conclusion seem wouldn't get if rid from the source code. And, the source code, ... is bitter and too dry.

I think write some code to do some analyse from the  code may be useful, however this should have a good direction, and, it is no there now.

Some links may need a mention for libreoffice :

- [How to build LibreOffice](https://www.libreoffice.org/about-us/source-code/) , I build it out, and notice the gbuild
- [gbuild: State of the LibreOffice build system](https://conference.libreoffice.org/talks/2013/content/sessions/050/files/LOConf2013_gbuild.pdf), A intrude to gbuild in 2013
- [Building System Page in WIki](https://wiki.documentfoundation.org/Development/Build_System)
- [Development/Learning Materials](https://wiki.documentfoundation.org/Development/Learning_Materials)
- [Modular Document](https://docs.libreoffice.org/)
- [Persona made by official design team](https://wiki.documentfoundation.org/Design/Guidelines/HIG_foundations#Persona)

I never contribute to libreoffice; and I may not a contributor to any popular open source project; but understanding is fun.

Well, sum up all, I think from practice, it should some research and reconsider inside libreoffice, thus go continue.

(XX) As a second path， we should consider build system in a Reasonable Way, for example, term and definition, formally abstract or concept. 

============================

Thanks for reading in so long. I don't think here is everything that must be realize, I write it down for a more possible "jump" to a good vision or anything fun.

Good Luck!

**Comment by Phytolizer** [comment]
> Sorry I don't know what is mean to "Porth but More", and how it connect to "morth".

Ah yeah, it's a bit of a pun, like "more porth". Porth is a programming language like Forth.

I think your model of what a build system should do is accurate. At first we can focus on just the compiler options and linking, and assume that dependencies are handled + incremental compilation is not needed.

Then later, we can add incremental compilation, and dependency management (since that is the hardest in my opinion).

I think we should start by trying to build simple projects first, then build our way up to LibreOffice.

**Comment by ltaoist** [comment]
> Ah yeah, it's a bit of a pun, like "more porth". Porth is a programming language like Forth.

Ha ha, I like pun.

Mainly I agree with we can start by trying to build simple projects first. Actually  I don't have a good know on compiler options/ linking, basically I know it is about hardware / specificed platform. Normally while I use gcc, I just -c to make .o file or -o to refer a out file name. And more, just put many name about .o file and make them up.

I already make a .bat for **building without a "building system" for "the building system"**; for some reason, this is not upload or be public. However it can be obtained like the [GNU make](https://www.gnu.org/software/make/manual/make.html) project:

<https://github.com/mirror/make/blob/master/build.sh#L2>

It do more, but may not XD accurate

And gcc is about 200+ options nowaday:

<https://gcc.gnu.org/onlinedocs/gcc-12.2.0/gcc/Invoking-GCC.html#Invoking-GCC>

It will be so so so so so so so so so so best for a list and categories for _compile stack member_, _compiler options_, _linking settings_, and so on. But I don't have a good idea for such list or categories.

Reason is quit importance, reason beat me down...

Or I do some dig for some small project?

Welcome for go more.

**Comment by Phytolizer** [comment]
The compiler options generally don't have much to do with the target platform, except stuff like `-march=` and `-mtune=`. The basics are completely platform independent, which makes our lives easier.

I think the only options we need worry about at first are:
- Warning flags (generally `-Wall`, `-Wextra`, `-Wpedantic`, and some others)
- Selecting C/C++ standard version (`-std=`)
- Debug and optimization flags (`-O` and `-g`)
- Include directories, link directories, and the like (`-I`, `-L`)
- Libraries to link (`-l`)

**Comment by Phytolizer** [comment]
Building libraries is indeed not cross platform, though. We'd need to fall back to `lib` on Windows, and `ar` everywhere else (these are for static libraries).

**Comment by ltaoist** [comment]
I agree with that we can start from a simpler case set. You figure out a good base.

Do I have a good understand of you comment -- We split compiler options into “platform depend” vs "platform independent", and the points is that the “platform depend” part, for building system should have a good fallback / connections for difference lib/ar or tools about module composition in a project ?

I know that linux commonly use .so, .o ，and windows use .dll, .obj ，for c/c++ the points is to header/source file locate, so the compile/linker can compile and link.

So what can we do? A interface that auto get the file path everything ?

**Comment by ltaoist** [comment]
Is a user should chose a compiler (eg, gcc/ clang/ msbuild compiler) on our building system, or he just focus on the code, library, the building system will just do everything as indeed?

**Comment by Phytolizer** [comment]
> We split compiler options into “platform depend” vs "platform independent", and the points is that the “platform depend” part, for building system should have a good fallback / connections for difference lib/ar or tools about module composition in a project ?

I think each tool / tool family should have some definition describing how it needs to be used to do its job.
For example, `ar`'s interface is *typically* `ar rcs liboutput.a input1.o input2.o ...`

> So what can we do? A interface that auto get the file path everything ?

I don't think that is possible unless we enforce a particular project structure. So essentially impossible, especially for larger projects.

> Is a user should chose a compiler (eg, gcc/ clang/ msbuild compiler) on our building system, or he just focus on the code, library, the building system will just do everything as indeed?

Yes, but maybe we should provide a default by testing to see which are available (this is extremely annoying/difficult on Windows in particular, because MSVC requires a particular batch file to set its environment, and the location of that batch file could be anywhere).

**Comment by ltaoist** [comment]
> I think each tool / tool family should have some definition describing how it needs to be used to do its job. For example, `ar`'s interface is _typically_ `ar rcs liboutput.a input1.o input2.o ...`

In summary, I surprised on you noticed `ar` . For `ar` may should consider in particularly, for to module is not always about compile or link, but to module is always about archive.

> > Is a user should chose a compiler (eg, gcc/ clang/ msbuild compiler) on our building system, or he just focus on the code, library, the building system will just do everything as indeed?
> 
> Yes, but maybe we should provide a default by testing to see which are available (this is extremely annoying/difficult on Windows in particular, because MSVC requires a particular batch file to set its environment, and the location of that batch file could be anywhere).

A "default+test" pattern easily perceived as a way can simplify things. But as a long observing and the law of balance in the physical world, that "default+test" pattern is just evil and would not make any effort. In short, a professor know a tool so they don't want the **default barrier**. A new comer may learn from default, but as more complexity coming, chaos coming, and the practice won't work at all. I generally think only the upstream maintainer can hold the "default+test" pattern for only they know the details, so they know the balance of default and availability.

But, considering on “archive” is intriguing. We don't provide "default", but we can provide “archive”. So, how can we make a “archive”  ? For example, what is a  >> atomic archive << ; can options or environment configuration be “archive” ? [let's ignore such problems like that the update of archive]. As a image, should we build an "archive base", and what has the identity to lay down on the base?

It won't worry about the path misleading in windows. Just scanning the C:\\ D:\\ E:\\ F:\\ .. if it is need. We can prompt that "For get the path of library, the building system will scan your disk. Continue? (Y/N)". If user input "N", it just quit.

**Comment by ltaoist** [comment]
I think we can be more in  a empiricism way. For empiricism, it is important for "count" and "statistics". Rules are not important.

**Comment by Phytolizer** [comment]
> It won't worry about the path misleading in windows. Just scanning the C:\ D:\ E:\ F:\ .. if it is need. We can prompt that "For get the path of library, the building system will scan your disk. Continue? (Y/N)". If user input "N", it just quit.

No, I absolutely do not want to scan the user's entire disk; that is the behavior of a malicious program. Most importantly because that process can take hours.

Regarding the default stuff, I was implying but didn't outright state that there would be an escape hatch to define your own toolchain, compiler paths, etc.

**Comment by ltaoist** [comment]
> 

It can has some "scan" strategy. For example, it would not search in a very deeply path, like C::/a/b/c/d/e/f/g/h/i/h/j/k/zlib/zlib.so. We can know that file system is hierarchical. We can just don't go into some directory, for example there is a not relative .exe files. Thinks that we need the position of "zlib.so", we don't go into a path seems not have "zlib.so" and just the path there is "zlib.so".

If it cost a long time, a fallback that quite the program itself, and prompt for user to input to the file path ?

As I know, [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) are do the lib finding in some way. And in windows, vs know many ms official development component.

**Comment by ltaoist** [comment]
Why we ( the building system ) are a right man to know the dependence, the archive source? Today a new software or a new program, especially a new c/c++ project, it would do a lot external linking, reference, reuse for difference functional and difference usage library or some utils. But we are not a god that knows everything c/c++ building, library... So how can the building system be in a coordinately way in between difference and variable program producing craft source ?

**Comment by Phytolizer** [comment]
Still, scanning drives at any level is wrong and going to get the build system flagged by virus scanners for good reason. The correct and supported way to find VS on Windows is by invoking vswhere, which is in a specified directory.

**Comment by ltaoist** [comment]
As I know there are some information in "The Windows Registry" for many installed application, and many program may use this for find program in public. But after reinstall the system, it will clear to no data. So, it will not always available for anytime even if a lib do in file system.

I don't create a building system for collect user's privacy. But it may be no a completed way to "invoking" in both linux or windows. But look at it optimistically, using windows API may be enough. I don't have a clear look, details may be found <https://social.msdn.microsoft.com/Forums/en-US/a695d031-4d3a-4636-b25a-faa0b70d2373/getting-installation-path-of-installed-application-through-windows-installer?forum=vcgeneral>.

Are these enough now？ In the first step, we should support that the basic functions included like this:

(1) know the correct compiler/linker/IDE path;
(2) support a way to invoke the lib files path;
(3) support a interface user input lib indeed to build a target program;
(4) support a interface user setup warning, language version, debug and optimization, include, and lib linking 
(5) a work build

**Comment by ltaoist** [comment]
Or just there are a way setup a var named "vswhere", and it is enough?

**Comment by Phytolizer** [comment]
vswhere is a program. It is installed with all modern VS versions. The
registry has nothing to do with it.

**Comment by ltaoist** [comment]
I install a vs edition on a windows, however I run "devenv" or "vswhere" on cmd, it cannot found...

Many build system do things "auto", but it is not any in-box fallback if something is lose, their just crash and commonly you need modified something or supply some options, and however, after a lots of years, I still cannot found what to do for resolving this; no document, do details, no internet found case...

Can't we have any innovation?

**Comment by Phytolizer** [comment]
https://github.com/microsoft/vswhere/wiki

It's in your program files, not on your PATH.

**Comment by ltaoist** [comment]
hello! I write some code for, supposing, a new system, named `stupidbuild` , I don't compile this ; just for a demonstration.

How would you feel this ? I notice that in `coolbuild` , some path utils and cmd invoke utils is ready, I even had not notice that, HAHA that is really radical useful.

```c++
// stupidbuild
#include <string>
#include <vector>

#define TEST_CASE_1

#define PROJECT_MORTH

namespace stupidbuild {
    
    // help utils
    void invoke_system_command(const char* program, ...);    
    std::string find_lib_path(const char* libname);

    // program kernel body
    class Kernel {
        public:
            Kernel();
        public:
            void SetupOptionsFromArgs(int argc, char** argv);
            void BuildMany(std::vector<std::string> targets);
            void Build(std::string target);
        private:
            int platform;
            int options_warning;
            int options_warning;
            int options_std_ver;
            int options_debug;
            int options_optimization;
            std::string options_redirected_main;
            std::vector<std::string> options_ext_library;
            std::vector<std::string> options_ext_include;
    };
    
    // impl
    
    /* 1 */
    void invoke_system_command(const char* program, ...){
        //
    }
    
    /* 2 */
    std::string find_lib_path(const char* libname){
        //
    }
    
        
    Kernel::Kernel(){};
    
    /*3 */
    void Kernel::SetupOptionsFromArgs(int argc, char** argv){
        int i =0;
        while(i < argc){
            if(!strcmp("--warning", argv[i])){
                if(++i >= argc){
                    error();
                }
                if(!strcmp("0", argv[i])){
                    options_warning = 0;
                }
                if(!strcmp("1", argv[i]) || !strcmp("all", argv[i])){
                    options_warning = 1;
                }
                continue;
            }
            if(!strcmp("--ext-lib", argv[i])){
                ++i;
                while(i < argc){
                    if(strstr(argv[i], "--") == 0){
                        continue;
                    }
                    options_ext_library.push_back(argv[i]);
                }
                continue;
            }
            ...
        }
    }
    
    void Kernel::BuildMany(const std::vector<std::string>& targets){
        for(auto target_iter = targets.begin(); target_iter != targets.end(); ++ target_iter){
            // build *target with options there were set up on Kernel, and so on
        }
    }
    
    void Kernel::Build(std::string target){
        //...
    }
    
};

#ifdef PROJECT_MORTH

std::vector<std::string> morth_primitive = {
        "args_iterator",
        "compile",
        "cross_reference",
        "load",
        "main",
        "nasm_emitter",
        "op",
        "parse",
        "run_command",
        "simulate",
        "stack",
        "token",
};

int main(int argc, char** argv){
    stupidbuild::Kernel kernel;
    kernel.SetupOptionsFromArgs(arc, argv);
    kernel.BuildMany(morth_primitive);
    kernel.Build("morth");
    return 0;
}

#endif
```

**Comment by ltaoist** [comment]
Hello, what is going on?

**Comment by Phytolizer** [comment]
Sorry, I've been busy. Feel free to create a repo for this C++ version, since the repo this issue is on is more about a C-based build system.

**Comment by ltaoist** [comment]
> Sorry, I've been busy. Feel free to create a repo for this C++ version, since the repo this issue is on is more about a C-based build system.

Is it a key point for on C/C++ ?

**Comment by ltaoist** [comment]
> Sorry, I've been busy. Feel free to create a repo for this C++ version, since the repo this issue is on is more about a C-based build system.

I don't come here for freedom. I come here for a knife.

I don't agree that some divided project / repo are always benefit. Is it possible that create an common sense so that a cowork would be possible? A critique of something is wrong, something is need included, something is interesting or not, something is good or bad, would not be better?

Cowork mean some job would give up, and some job would be focus.

**Comment by Phytolizer** [comment]
It wouldn't really mean a division. I'm not working on the C code in this repo, which is why I think it'd make more sense for a different repo to be active.

**Comment by ltaoist** [comment]
> It wouldn't really mean a division. I'm not working on the C code in this repo, which is why I think it'd make more sense for a different repo to be active.

I don't want to "own" a repo, for many reason …… typically, that is about democracy; I invite, but you can have more privileges until enough; for a good cowork. I have no talent to be a great dictator.

However, on other side, is this possible that start from a “historied”? Start from a blank board may cause just lost.

As my impression, you have a nice "cutting power". As in product producing procedure, "cutting power" is important, people may be frightened in buying a Christmas trees with many vertical branch.

**Comment by ltaoist** [comment]
Is it possible that we next to focus some _domain_ ? How about we continue to consider a specific domain _some_ software that can build on the building system?

:-P

**Comment by Phytolizer** [comment]
> I don't want to "own" a repo, for many reason

We can always make a GitHub org with each member having equal ownership. Or I can make the repo, doesn't much matter.

> However, on other side, is this possible that start from a “historied”? Start from a blank board may cause just lost.

I do think that starting from scratch in C++ would be better than attempting to port the tangled web of C macros I wrote.

> Is it possible that we next to focus some domain ? How about we continue to consider a specific domain some software that can build on the building system?

Absolutely. We can start by trying to build a single-file project and scale up from there.

**Comment by ltaoist** [comment]
> We can always make a GitHub org with each member having equal ownership. Or I can make the repo, doesn't much matter.

> I do think that starting from scratch in C++ would be better than attempting to port the tangled web of C macros I wrote.

I think you are right.

Sorry for my brain blocked recently; and I infected with COVID since Tuesday; but it seems that I'm on the verge of recovery. Actually yesterday I eat some fruit can.

I new a Github org called "punblock" and invited you. Sorry I don't know how a give a nice name. Feel free to give a new name.

I feel you say "tangled" is , haha, some humor, and haha, some "authentic". And after I doing some internet search, "Tangled" is also a disney animated film.

> Absolutely. We can start by trying to build a single-file project and scale up from there.

How to bootstrap up? Port the c++ above to the new org repo and write some examine？

**Comment by ltaoist** [comment]
Should I close this issue and will continue to discussion in the new repo issue board?

**Comment by Phytolizer** [comment]
Yes, I'll close it.
